type Account @entity {
	id:                           ID!
	tokens:                       [Token!]! @derivedFrom(field: "owner")
	delegationsOwner:             [OperatorDelegation!]! @derivedFrom(field: "owner")
	delegationsOperator:          [OperatorDelegation!]! @derivedFrom(field: "operator")
	transfersFrom:                [Transfer!]! @derivedFrom(field: "from")
	transfersTo:                  [Transfer!]! @derivedFrom(field: "to")
	approvalsOwner:               [Approval!]! @derivedFrom(field: "owner")
	approvalsApproved:            [Approval!]! @derivedFrom(field: "approved")
	approvalsForAllOwner:         [ApprovalForAll!]! @derivedFrom(field: "owner")
	approvalsForAllOperator:      [ApprovalForAll!]! @derivedFrom(field: "operator")
}

type Token @entity {
	id:                           ID!
	identifier:                   BigInt!
	owner:                        Account!
	approval:                     Account
	event:                        PoapEvent!
	transfers:                    [Transfer!]! @derivedFrom(field: "token")
	approvals:                    [Approval!]! @derivedFrom(field: "token")
}

type OperatorDelegation @entity {
	id:                           ID!
	owner:                        Account!
	operator:                     Account!
	approved:                     Boolean!
	events:                       [ApprovalForAll!]! @derivedFrom(field: "delegation")
}

type PoapEvent @entity {
	id:                           ID!
	tokens:                       [Token!]! @derivedFrom(field: "event")
}

type Transfer implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	token:                        Token!
	from:                         Account!
	to:                           Account!
}

type Approval implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	token:                        Token!
	owner:                        Account!
	approved:                     Account!
}

type ApprovalForAll implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	delegation:                   OperatorDelegation!
	owner:                        Account!
	operator:                     Account!
	approved:                     Boolean!
}
