type Account @entity {
	id:                           ID!

	asGovernor:                   Governor
	asToken:                      Token
	asTimelock:                   Timelock

	compFor:                      [Governor!]! @derivedFrom(field: "comp")
	timelockFor:                  [Governor!]! @derivedFrom(field: "timelock")
	guardianFor:                  [Governor!]! @derivedFrom(field: "guardian")
	adminForGovernor:             [Governor!]! @derivedFrom(field: "admin")
	pendingAdminForGovernor:      [Governor!]! @derivedFrom(field: "pendingAdmin")
	implementationForGovernor:    [Governor!]! @derivedFrom(field: "implementation")
	proposals:                    [Proposal!]! @derivedFrom(field: "proposer")
	targetedCalls:                [ProposalCall!]! @derivedFrom(field: "target")
	receipts:                     [Receipt!]! @derivedFrom(field: "voter")
	proposalCreated:              [ProposalCreated!]! @derivedFrom(field: "proposer")
	votecast:                     [VoteCast!]! @derivedFrom(field: "voter")

	balances:                     [Balance!]! @derivedFrom(field: "account")
	transfersFrom:                [Transfer!]! @derivedFrom(field: "from")
	transfersTo:                  [Transfer!]! @derivedFrom(field: "to")
	approvalsOwner:               [Approval!]! @derivedFrom(field: "owner")
	approvalsSpender:             [Approval!]! @derivedFrom(field: "spender")

	adminForTimelock:             [Timelock!]! @derivedFrom(field: "admin")
	pendingAdminForTimelock:      [Timelock!]! @derivedFrom(field: "pendingAdmin")
	targetedTransactions:         [TimelockTransaction!]! @derivedFrom(field: "target")
}

###############################################################################
#                                  Governor                                   #
###############################################################################
enum GovernorType {
	ALPHA
	BRAVO
}

type Governor @entity {
	id:                           ID!
	type:                         GovernorType!
	name:                         String # optional ? → missing in some forks
	comp:                         Account # optional ? → missing/renames in some forks
	timelock:                     Account # optional ?
	guardian:                     Account # part of GovernorAlpha
	admin:                        Account # part of GovernorBravo
	pendingAdmin:                 Account # part of GovernorBravo
	implementation:               Account # part of GovernorBravo
	quorumVotes:                  BigInt # optional ?
	proposalThreshold:            BigInt # optional ?
	proposalMaxOperations:        BigInt # optional ?
	votingDelay:                  BigInt # optional ?
	votingPeriod:                 BigInt # optional ?
	proposalCount:                Int!
	queuedProposalCount:          Int!
	executedProposalCount:        Int!
	canceledProposalCount:        Int!
	proposals:                    [Proposal!]! @derivedFrom(field: "governor")
	proposalCreated:              [ProposalCreated!]! @derivedFrom(field: "governor")
	proposalQueued:               [ProposalQueued!]! @derivedFrom(field: "governor")
	proposalExecuted:             [ProposalExecuted!]! @derivedFrom(field: "governor")
	proposalCanceled:             [ProposalCanceled!]! @derivedFrom(field: "governor")
	votecast:                     [VoteCast!]! @derivedFrom(field: "governor")
	newAdmin:                     [NewGovernanceAdmin!]! @derivedFrom(field: "governor")
	newPendingAdmin:              [NewGovernancePendingAdmin!]! @derivedFrom(field: "governor")
	newImplementation:            [NewGovernanceImplementation!]! @derivedFrom(field: "governor")
	proposalThresholdSet:         [ProposalThresholdSet!]! @derivedFrom(field: "governor")
	votingDelaySet:               [VotingDelaySet!]! @derivedFrom(field: "governor")
	votingPeriodSet:              [VotingPeriodSet!]! @derivedFrom(field: "governor")
}

type Proposal @entity {
	id:                           ID!
	governor:                     Governor!
	proposalId:                   BigInt!
	proposer:                     Account!
	eta:                          BigInt # not set until queue
	startBlock:                   BigInt # missing in some forks
	endBlock:                     BigInt # missing in some forks
	forVotes:                     DecimalValue!
	againstVotes:                 DecimalValue!
	abstainVotes:                 DecimalValue!
	canceled:                     Boolean!
	executed:                     Boolean!
	title:                        String # extension
	description:                  String # optional ?
	calls:                        [ProposalCall!]! @derivedFrom(field: "proposal")
	receipts:                     [Receipt!]! @derivedFrom(field: "proposal")
	proposalCreated:              [ProposalCreated!]! @derivedFrom(field: "proposal")
	proposalQueued:               [ProposalQueued!]! @derivedFrom(field: "proposal")
	proposalExecuted:             [ProposalExecuted!]! @derivedFrom(field: "proposal")
	proposalCanceled:             [ProposalCanceled!]! @derivedFrom(field: "proposal")
	votecast:                     [VoteCast!]! @derivedFrom(field: "proposal")
}

type ProposalCall @entity {
	id:                           ID!
	proposal:                     Proposal!
	index:                        Int!
	target:                       Account!
	value:                        BigInt
	signature:                    String
	calldata:                     Bytes
}

enum Support {
	AGAINST
	FOR
	ABSTAIN
}

type Receipt @entity {
	id:                           ID!
	proposal:                     Proposal!
	voter:                        Account!
	support:                      Support!
	votes:                        DecimalValue!
	votesExact:                   BigInt!
}

type ProposalCreated implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	governor:                     Governor!
	proposal:                     Proposal!
	proposer:                     Account!
}

type ProposalQueued implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	governor:                     Governor!
	proposal:                     Proposal!
	eta:                          BigInt!
}

type ProposalExecuted implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	governor:                     Governor!
	proposal:                     Proposal!
}

type ProposalCanceled implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	governor:                     Governor!
	proposal:                     Proposal!
}

type VoteCast implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	governor:                     Governor!
	proposal:                     Proposal!
	receipt:                      Receipt!
	voter:                        Account!
}

type NewGovernanceAdmin implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	governor:                     Governor!
	oldAdmin:                     Account!
	newAdmin:                     Account!
}

type NewGovernancePendingAdmin implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	governor:                     Governor!
	oldPendingAdmin:              Account!
	newPendingAdmin:              Account!
}

type NewGovernanceImplementation implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	governor:                     Governor!
	oldImplementation:            Account!
	newImplementation:            Account!
}

type ProposalThresholdSet implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	governor:                     Governor!
	oldProposalThreshold:         BigInt!
	newProposalThreshold:         BigInt!
}

type VotingDelaySet implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	governor:                     Governor!
	oldVotingDelay:               BigInt!
	newVotingDelay:               BigInt!
}

type VotingPeriodSet implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	governor:                     Governor!
	oldVotingPeriod:              BigInt!
	newVotingPeriod:              BigInt!
}

###############################################################################
#                                  Timelock                                   #
###############################################################################
type Timelock @entity {
	id:                           ID!
	admin:                        Account
	pendingAdmin:                 Account
	delay:                        BigInt
	GRACE_PERIOD:                 BigInt
	MINIMUM_DELAY:                BigInt
	MAXIMUM_DELAY:                BigInt
	transactions:                 [TimelockTransaction!]! @derivedFrom(field: "timelock")
	transactionsQueued:           [TimelockQueueTransaction!]! @derivedFrom(field: "timelock")
	transactionsExecuted:         [TimelockExecuteTransaction!]! @derivedFrom(field: "timelock")
	transactionsCanceled:         [TimelockCancelTransaction!]! @derivedFrom(field: "timelock")
	newAdmins:                    [NewTimelockAdmin!]! @derivedFrom(field: "timelock")
	newPendingAdmins:             [NewTimelockPendingAdmin!]! @derivedFrom(field: "timelock")
	delaySet:                     [NewTimelockDelay!]! @derivedFrom(field: "timelock")
}

type TimelockTransaction @entity {
	id:                           ID!
	txHash:                       Bytes!
	timelock:                     Timelock!
	target:                       Account
	value:                        BigInt
	signature:                    String
	data:                         Bytes
	eta:                          BigInt
	canceled:                     Boolean!
	executed:                     Boolean!
}

type TimelockQueueTransaction implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	timelock:                     Timelock!
	tx:                           TimelockTransaction!
}

type TimelockExecuteTransaction implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	timelock:                     Timelock!
	tx:                           TimelockTransaction!
}

type TimelockCancelTransaction implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	timelock:                     Timelock!
	tx:                           TimelockTransaction!
}

type NewTimelockDelay implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	timelock:                     Timelock!
	newDelay:                     BigInt!
}

type NewTimelockAdmin implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	timelock:                     Timelock!
	newAdmin:                     Account!
}

type NewTimelockPendingAdmin implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	timelock:                     Timelock!
	newPendingAdmin:              Account!
}

###############################################################################
#                                ERC20 + Comp                                 #
###############################################################################
type Token @entity {
	id:                           ID!
	name:                         String
	symbol:                       String
	decimals:                     Int!
	balances:                     [Balance!]! @derivedFrom(field: "token")
	transfers:                    [Transfer!]! @derivedFrom(field: "token")
	approvals:                    [Approval!]! @derivedFrom(field: "token")
}

type Balance @entity {
	id:                           ID!
	token:                        Token!
	account:                      Account!
	value:                        DecimalValue!
	valueExact:                   BigInt!
	voting:                       DecimalValue!
	votingExact:                  BigInt!
	delegate:                     Balance
	delegatorsCount:              Int!
	transfersFrom:                [Transfer!]! @derivedFrom(field: "fromBalance")
	transfersTo:                  [Transfer!]! @derivedFrom(field: "toBalance")
	delegators:                   [Balance!]! @derivedFrom(field: "delegate")
}

type Transfer implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	token:                        Token!
	from:                         Account!
	fromBalance:                  Balance
	to:                           Account!
	toBalance:                    Balance
	value:                        BigDecimal!
}

type Approval implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	token:                        Token!
	owner:                        Account!
	spender:                      Account!
	value:                        BigDecimal!
}

type DelegateChanged implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	token:                        Token!
	delegator:                    Account!
	fromDelegate:                 Account!
	toDelegate:                   Account!
}

type DelegateVotesChanged implements Event @entity {
	id:                           ID!
	transaction:                  Transaction!
	timestamp:                    BigInt!
	token:                        Token!
	delegate:                     Account!
	balance:                      BigDecimal!
}
